### ISSUE TITLE
Game over when using undo button after continue with 100 coins

### ISSUE THREAD

**Issue by ljahn** [adil192/ricochlime#43] opened 2024-05-29 19:03 UTC
If you use the undo button directly after continuing using 100 coins, it undoes not only your move, but also all monsters that were removed by using the 100 coins are back, leading to immediate game over.

Ideally the monsters should not be back.

I am on version 1.5.0 from F-Droid. I checked the recent commits up to 1.5.2, it does not seem like this was fixed already.

**Comment by adil192** [comment] 2024-05-29 20:02
Duplicate of #42

**Closed by adil192** 2024-05-29 20:02 UTC

**Comment by ljahn** [comment] 2024-05-29 20:39
Sorry, I did not connect "subtracted doubly" with my "game over" situation (did not have enough to pay twice 😉 )
Nice that it's already fixed, Thanks 👍
